// source: io/member/program.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() {
  if (this) { return this; }
  if (typeof window !== 'undefined') { return window; }
  if (typeof global !== 'undefined') { return global; }
  if (typeof self !== 'undefined') { return self; }
  return Function('return this')();
}.call(null));

var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js');
goog.object.extend(proto, google_protobuf_timestamp_pb);
var io_common_distribution_pb = require('../../io/common/distribution_pb.js');
goog.object.extend(proto, io_common_distribution_pb);
var io_common_localization_pb = require('../../io/common/localization_pb.js');
goog.object.extend(proto, io_common_localization_pb);
var io_common_metrics_pb = require('../../io/common/metrics_pb.js');
goog.object.extend(proto, io_common_metrics_pb);
var io_common_project_pb = require('../../io/common/project_pb.js');
goog.object.extend(proto, io_common_project_pb);
var io_common_billing_pb = require('../../io/common/billing_pb.js');
goog.object.extend(proto, io_common_billing_pb);
goog.exportSymbol('proto.members.BalanceType', null, global);
goog.exportSymbol('proto.members.CustomExternalId', null, global);
goog.exportSymbol('proto.members.EventCaptureSettings', null, global);
goog.exportSymbol('proto.members.GetMetaKeysResponse', null, global);
goog.exportSymbol('proto.members.ListProgramsResponse', null, global);
goog.exportSymbol('proto.members.PassRecoverySettings', null, global);
goog.exportSymbol('proto.members.PointsType', null, global);
goog.exportSymbol('proto.members.ProfileImageSetting', null, global);
goog.exportSymbol('proto.members.Program', null, global);
goog.exportSymbol('proto.members.ProgramAutoUpDownGradeTierType', null, global);
goog.exportSymbol('proto.members.ProgramCopyRequest', null, global);
goog.exportSymbol('proto.members.RecoverPassDelivery', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.members.PointsType = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.members.PointsType, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.members.PointsType.displayName = 'proto.members.PointsType';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.members.Program = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.members.Program.repeatedFields_, null);
};
goog.inherits(proto.members.Program, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.members.Program.displayName = 'proto.members.Program';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.members.EventCaptureSettings = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.members.EventCaptureSettings, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.members.EventCaptureSettings.displayName = 'proto.members.EventCaptureSettings';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.members.ProgramCopyRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.members.ProgramCopyRequest.repeatedFields_, null);
};
goog.inherits(proto.members.ProgramCopyRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.members.ProgramCopyRequest.displayName = 'proto.members.ProgramCopyRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.members.ListProgramsResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.members.ListProgramsResponse.repeatedFields_, null);
};
goog.inherits(proto.members.ListProgramsResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.members.ListProgramsResponse.displayName = 'proto.members.ListProgramsResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.members.GetMetaKeysResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.members.GetMetaKeysResponse.repeatedFields_, null);
};
goog.inherits(proto.members.GetMetaKeysResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.members.GetMetaKeysResponse.displayName = 'proto.members.GetMetaKeysResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.members.CustomExternalId = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.members.CustomExternalId, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.members.CustomExternalId.displayName = 'proto.members.CustomExternalId';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.members.PassRecoverySettings = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.members.PassRecoverySettings.repeatedFields_, null);
};
goog.inherits(proto.members.PassRecoverySettings, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.members.PassRecoverySettings.displayName = 'proto.members.PassRecoverySettings';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.members.PointsType.prototype.toObject = function(opt_includeInstance) {
  return proto.members.PointsType.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.members.PointsType} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.members.PointsType.toObject = function(includeInstance, msg) {
  var f, obj = {
    balancetype: jspb.Message.getFieldWithDefault(msg, 1, 0),
    currencycode: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.members.PointsType}
 */
proto.members.PointsType.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.members.PointsType;
  return proto.members.PointsType.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.members.PointsType} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.members.PointsType}
 */
proto.members.PointsType.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.members.BalanceType} */ (reader.readEnum());
      msg.setBalancetype(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setCurrencycode(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.members.PointsType.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.members.PointsType.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.members.PointsType} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.members.PointsType.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getBalancetype();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getCurrencycode();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional BalanceType balanceType = 1;
 * @return {!proto.members.BalanceType}
 */
proto.members.PointsType.prototype.getBalancetype = function() {
  return /** @type {!proto.members.BalanceType} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.members.BalanceType} value
 * @return {!proto.members.PointsType} returns this
 */
proto.members.PointsType.prototype.setBalancetype = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional string currencyCode = 2;
 * @return {string}
 */
proto.members.PointsType.prototype.getCurrencycode = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.members.PointsType} returns this
 */
proto.members.PointsType.prototype.setCurrencycode = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.members.Program.repeatedFields_ = [4,20];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.members.Program.prototype.toObject = function(opt_includeInstance) {
  return proto.members.Program.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.members.Program} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.members.Program.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, ""),
    name: jspb.Message.getFieldWithDefault(msg, 2, ""),
    localizedname: (f = msg.getLocalizedname()) && io_common_localization_pb.LocalizedString.toObject(includeInstance, f),
    statusList: (f = jspb.Message.getRepeatedField(msg, 4)) == null ? undefined : f,
    quota: (f = msg.getQuota()) && io_common_billing_pb.Quota.toObject(includeInstance, f),
    passtypeidentifier: jspb.Message.getFieldWithDefault(msg, 6, ""),
    distributionsettings: (f = msg.getDistributionsettings()) && io_common_distribution_pb.DistributionSettings.toObject(includeInstance, f),
    autodeletedaysafterexpiry: jspb.Message.getFieldWithDefault(msg, 8, 0),
    expirymessage: jspb.Message.getFieldWithDefault(msg, 10, ""),
    localizedexpirymessage: (f = msg.getLocalizedexpirymessage()) && io_common_localization_pb.LocalizedString.toObject(includeInstance, f),
    pointstype: (f = msg.getPointstype()) && proto.members.PointsType.toObject(includeInstance, f),
    secondarypointstype: (f = msg.getSecondarypointstype()) && proto.members.PointsType.toObject(includeInstance, f),
    metrics: (f = msg.getMetrics()) && io_common_metrics_pb.Metrics.toObject(includeInstance, f),
    metafieldslistList: (f = jspb.Message.getRepeatedField(msg, 20)) == null ? undefined : f,
    created: (f = msg.getCreated()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    updated: (f = msg.getUpdated()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    profileimagesettings: jspb.Message.getFieldWithDefault(msg, 23, 0),
    applyfieldtoexternalidonenrol: (f = msg.getApplyfieldtoexternalidonenrol()) && proto.members.CustomExternalId.toObject(includeInstance, f),
    eventcapturesettings: (f = msg.getEventcapturesettings()) && proto.members.EventCaptureSettings.toObject(includeInstance, f),
    passrecoverysettings: (f = msg.getPassrecoverysettings()) && proto.members.PassRecoverySettings.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.members.Program}
 */
proto.members.Program.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.members.Program;
  return proto.members.Program.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.members.Program} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.members.Program}
 */
proto.members.Program.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 3:
      var value = new io_common_localization_pb.LocalizedString;
      reader.readMessage(value,io_common_localization_pb.LocalizedString.deserializeBinaryFromReader);
      msg.setLocalizedname(value);
      break;
    case 4:
      var values = /** @type {!Array<!proto.io.ProjectStatus>} */ (reader.isDelimited() ? reader.readPackedEnum() : [reader.readEnum()]);
      for (var i = 0; i < values.length; i++) {
        msg.addStatus(values[i]);
      }
      break;
    case 5:
      var value = new io_common_billing_pb.Quota;
      reader.readMessage(value,io_common_billing_pb.Quota.deserializeBinaryFromReader);
      msg.setQuota(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setPasstypeidentifier(value);
      break;
    case 7:
      var value = new io_common_distribution_pb.DistributionSettings;
      reader.readMessage(value,io_common_distribution_pb.DistributionSettings.deserializeBinaryFromReader);
      msg.setDistributionsettings(value);
      break;
    case 8:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setAutodeletedaysafterexpiry(value);
      break;
    case 10:
      var value = /** @type {string} */ (reader.readString());
      msg.setExpirymessage(value);
      break;
    case 11:
      var value = new io_common_localization_pb.LocalizedString;
      reader.readMessage(value,io_common_localization_pb.LocalizedString.deserializeBinaryFromReader);
      msg.setLocalizedexpirymessage(value);
      break;
    case 16:
      var value = new proto.members.PointsType;
      reader.readMessage(value,proto.members.PointsType.deserializeBinaryFromReader);
      msg.setPointstype(value);
      break;
    case 17:
      var value = new proto.members.PointsType;
      reader.readMessage(value,proto.members.PointsType.deserializeBinaryFromReader);
      msg.setSecondarypointstype(value);
      break;
    case 19:
      var value = new io_common_metrics_pb.Metrics;
      reader.readMessage(value,io_common_metrics_pb.Metrics.deserializeBinaryFromReader);
      msg.setMetrics(value);
      break;
    case 20:
      var value = /** @type {string} */ (reader.readString());
      msg.addMetafieldslist(value);
      break;
    case 21:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setCreated(value);
      break;
    case 22:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setUpdated(value);
      break;
    case 23:
      var value = /** @type {!proto.members.ProfileImageSetting} */ (reader.readEnum());
      msg.setProfileimagesettings(value);
      break;
    case 24:
      var value = new proto.members.CustomExternalId;
      reader.readMessage(value,proto.members.CustomExternalId.deserializeBinaryFromReader);
      msg.setApplyfieldtoexternalidonenrol(value);
      break;
    case 25:
      var value = new proto.members.EventCaptureSettings;
      reader.readMessage(value,proto.members.EventCaptureSettings.deserializeBinaryFromReader);
      msg.setEventcapturesettings(value);
      break;
    case 26:
      var value = new proto.members.PassRecoverySettings;
      reader.readMessage(value,proto.members.PassRecoverySettings.deserializeBinaryFromReader);
      msg.setPassrecoverysettings(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.members.Program.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.members.Program.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.members.Program} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.members.Program.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getLocalizedname();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      io_common_localization_pb.LocalizedString.serializeBinaryToWriter
    );
  }
  f = message.getStatusList();
  if (f.length > 0) {
    writer.writePackedEnum(
      4,
      f
    );
  }
  f = message.getQuota();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      io_common_billing_pb.Quota.serializeBinaryToWriter
    );
  }
  f = message.getPasstypeidentifier();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getDistributionsettings();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      io_common_distribution_pb.DistributionSettings.serializeBinaryToWriter
    );
  }
  f = message.getAutodeletedaysafterexpiry();
  if (f !== 0) {
    writer.writeUint32(
      8,
      f
    );
  }
  f = message.getExpirymessage();
  if (f.length > 0) {
    writer.writeString(
      10,
      f
    );
  }
  f = message.getLocalizedexpirymessage();
  if (f != null) {
    writer.writeMessage(
      11,
      f,
      io_common_localization_pb.LocalizedString.serializeBinaryToWriter
    );
  }
  f = message.getPointstype();
  if (f != null) {
    writer.writeMessage(
      16,
      f,
      proto.members.PointsType.serializeBinaryToWriter
    );
  }
  f = message.getSecondarypointstype();
  if (f != null) {
    writer.writeMessage(
      17,
      f,
      proto.members.PointsType.serializeBinaryToWriter
    );
  }
  f = message.getMetrics();
  if (f != null) {
    writer.writeMessage(
      19,
      f,
      io_common_metrics_pb.Metrics.serializeBinaryToWriter
    );
  }
  f = message.getMetafieldslistList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      20,
      f
    );
  }
  f = message.getCreated();
  if (f != null) {
    writer.writeMessage(
      21,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getUpdated();
  if (f != null) {
    writer.writeMessage(
      22,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getProfileimagesettings();
  if (f !== 0.0) {
    writer.writeEnum(
      23,
      f
    );
  }
  f = message.getApplyfieldtoexternalidonenrol();
  if (f != null) {
    writer.writeMessage(
      24,
      f,
      proto.members.CustomExternalId.serializeBinaryToWriter
    );
  }
  f = message.getEventcapturesettings();
  if (f != null) {
    writer.writeMessage(
      25,
      f,
      proto.members.EventCaptureSettings.serializeBinaryToWriter
    );
  }
  f = message.getPassrecoverysettings();
  if (f != null) {
    writer.writeMessage(
      26,
      f,
      proto.members.PassRecoverySettings.serializeBinaryToWriter
    );
  }
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.members.Program.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.members.Program} returns this
 */
proto.members.Program.prototype.setId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string name = 2;
 * @return {string}
 */
proto.members.Program.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.members.Program} returns this
 */
proto.members.Program.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional io.LocalizedString localizedName = 3;
 * @return {?proto.io.LocalizedString}
 */
proto.members.Program.prototype.getLocalizedname = function() {
  return /** @type{?proto.io.LocalizedString} */ (
    jspb.Message.getWrapperField(this, io_common_localization_pb.LocalizedString, 3));
};


/**
 * @param {?proto.io.LocalizedString|undefined} value
 * @return {!proto.members.Program} returns this
*/
proto.members.Program.prototype.setLocalizedname = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.members.Program} returns this
 */
proto.members.Program.prototype.clearLocalizedname = function() {
  return this.setLocalizedname(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.members.Program.prototype.hasLocalizedname = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * repeated io.ProjectStatus status = 4;
 * @return {!Array<!proto.io.ProjectStatus>}
 */
proto.members.Program.prototype.getStatusList = function() {
  return /** @type {!Array<!proto.io.ProjectStatus>} */ (jspb.Message.getRepeatedField(this, 4));
};


/**
 * @param {!Array<!proto.io.ProjectStatus>} value
 * @return {!proto.members.Program} returns this
 */
proto.members.Program.prototype.setStatusList = function(value) {
  return jspb.Message.setField(this, 4, value || []);
};


/**
 * @param {!proto.io.ProjectStatus} value
 * @param {number=} opt_index
 * @return {!proto.members.Program} returns this
 */
proto.members.Program.prototype.addStatus = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 4, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.members.Program} returns this
 */
proto.members.Program.prototype.clearStatusList = function() {
  return this.setStatusList([]);
};


/**
 * optional io.Quota quota = 5;
 * @return {?proto.io.Quota}
 */
proto.members.Program.prototype.getQuota = function() {
  return /** @type{?proto.io.Quota} */ (
    jspb.Message.getWrapperField(this, io_common_billing_pb.Quota, 5));
};


/**
 * @param {?proto.io.Quota|undefined} value
 * @return {!proto.members.Program} returns this
*/
proto.members.Program.prototype.setQuota = function(value) {
  return jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.members.Program} returns this
 */
proto.members.Program.prototype.clearQuota = function() {
  return this.setQuota(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.members.Program.prototype.hasQuota = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional string passTypeIdentifier = 6;
 * @return {string}
 */
proto.members.Program.prototype.getPasstypeidentifier = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.members.Program} returns this
 */
proto.members.Program.prototype.setPasstypeidentifier = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional io.DistributionSettings distributionSettings = 7;
 * @return {?proto.io.DistributionSettings}
 */
proto.members.Program.prototype.getDistributionsettings = function() {
  return /** @type{?proto.io.DistributionSettings} */ (
    jspb.Message.getWrapperField(this, io_common_distribution_pb.DistributionSettings, 7));
};


/**
 * @param {?proto.io.DistributionSettings|undefined} value
 * @return {!proto.members.Program} returns this
*/
proto.members.Program.prototype.setDistributionsettings = function(value) {
  return jspb.Message.setWrapperField(this, 7, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.members.Program} returns this
 */
proto.members.Program.prototype.clearDistributionsettings = function() {
  return this.setDistributionsettings(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.members.Program.prototype.hasDistributionsettings = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional uint32 autoDeleteDaysAfterExpiry = 8;
 * @return {number}
 */
proto.members.Program.prototype.getAutodeletedaysafterexpiry = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 8, 0));
};


/**
 * @param {number} value
 * @return {!proto.members.Program} returns this
 */
proto.members.Program.prototype.setAutodeletedaysafterexpiry = function(value) {
  return jspb.Message.setProto3IntField(this, 8, value);
};


/**
 * optional string expiryMessage = 10;
 * @return {string}
 */
proto.members.Program.prototype.getExpirymessage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 10, ""));
};


/**
 * @param {string} value
 * @return {!proto.members.Program} returns this
 */
proto.members.Program.prototype.setExpirymessage = function(value) {
  return jspb.Message.setProto3StringField(this, 10, value);
};


/**
 * optional io.LocalizedString localizedExpiryMessage = 11;
 * @return {?proto.io.LocalizedString}
 */
proto.members.Program.prototype.getLocalizedexpirymessage = function() {
  return /** @type{?proto.io.LocalizedString} */ (
    jspb.Message.getWrapperField(this, io_common_localization_pb.LocalizedString, 11));
};


/**
 * @param {?proto.io.LocalizedString|undefined} value
 * @return {!proto.members.Program} returns this
*/
proto.members.Program.prototype.setLocalizedexpirymessage = function(value) {
  return jspb.Message.setWrapperField(this, 11, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.members.Program} returns this
 */
proto.members.Program.prototype.clearLocalizedexpirymessage = function() {
  return this.setLocalizedexpirymessage(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.members.Program.prototype.hasLocalizedexpirymessage = function() {
  return jspb.Message.getField(this, 11) != null;
};


/**
 * optional PointsType pointsType = 16;
 * @return {?proto.members.PointsType}
 */
proto.members.Program.prototype.getPointstype = function() {
  return /** @type{?proto.members.PointsType} */ (
    jspb.Message.getWrapperField(this, proto.members.PointsType, 16));
};


/**
 * @param {?proto.members.PointsType|undefined} value
 * @return {!proto.members.Program} returns this
*/
proto.members.Program.prototype.setPointstype = function(value) {
  return jspb.Message.setWrapperField(this, 16, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.members.Program} returns this
 */
proto.members.Program.prototype.clearPointstype = function() {
  return this.setPointstype(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.members.Program.prototype.hasPointstype = function() {
  return jspb.Message.getField(this, 16) != null;
};


/**
 * optional PointsType secondaryPointsType = 17;
 * @return {?proto.members.PointsType}
 */
proto.members.Program.prototype.getSecondarypointstype = function() {
  return /** @type{?proto.members.PointsType} */ (
    jspb.Message.getWrapperField(this, proto.members.PointsType, 17));
};


/**
 * @param {?proto.members.PointsType|undefined} value
 * @return {!proto.members.Program} returns this
*/
proto.members.Program.prototype.setSecondarypointstype = function(value) {
  return jspb.Message.setWrapperField(this, 17, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.members.Program} returns this
 */
proto.members.Program.prototype.clearSecondarypointstype = function() {
  return this.setSecondarypointstype(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.members.Program.prototype.hasSecondarypointstype = function() {
  return jspb.Message.getField(this, 17) != null;
};


/**
 * optional io.Metrics metrics = 19;
 * @return {?proto.io.Metrics}
 */
proto.members.Program.prototype.getMetrics = function() {
  return /** @type{?proto.io.Metrics} */ (
    jspb.Message.getWrapperField(this, io_common_metrics_pb.Metrics, 19));
};


/**
 * @param {?proto.io.Metrics|undefined} value
 * @return {!proto.members.Program} returns this
*/
proto.members.Program.prototype.setMetrics = function(value) {
  return jspb.Message.setWrapperField(this, 19, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.members.Program} returns this
 */
proto.members.Program.prototype.clearMetrics = function() {
  return this.setMetrics(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.members.Program.prototype.hasMetrics = function() {
  return jspb.Message.getField(this, 19) != null;
};


/**
 * repeated string metaFieldsList = 20;
 * @return {!Array<string>}
 */
proto.members.Program.prototype.getMetafieldslistList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 20));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.members.Program} returns this
 */
proto.members.Program.prototype.setMetafieldslistList = function(value) {
  return jspb.Message.setField(this, 20, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.members.Program} returns this
 */
proto.members.Program.prototype.addMetafieldslist = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 20, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.members.Program} returns this
 */
proto.members.Program.prototype.clearMetafieldslistList = function() {
  return this.setMetafieldslistList([]);
};


/**
 * optional google.protobuf.Timestamp created = 21;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.members.Program.prototype.getCreated = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 21));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.members.Program} returns this
*/
proto.members.Program.prototype.setCreated = function(value) {
  return jspb.Message.setWrapperField(this, 21, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.members.Program} returns this
 */
proto.members.Program.prototype.clearCreated = function() {
  return this.setCreated(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.members.Program.prototype.hasCreated = function() {
  return jspb.Message.getField(this, 21) != null;
};


/**
 * optional google.protobuf.Timestamp updated = 22;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.members.Program.prototype.getUpdated = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 22));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.members.Program} returns this
*/
proto.members.Program.prototype.setUpdated = function(value) {
  return jspb.Message.setWrapperField(this, 22, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.members.Program} returns this
 */
proto.members.Program.prototype.clearUpdated = function() {
  return this.setUpdated(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.members.Program.prototype.hasUpdated = function() {
  return jspb.Message.getField(this, 22) != null;
};


/**
 * optional ProfileImageSetting profileImageSettings = 23;
 * @return {!proto.members.ProfileImageSetting}
 */
proto.members.Program.prototype.getProfileimagesettings = function() {
  return /** @type {!proto.members.ProfileImageSetting} */ (jspb.Message.getFieldWithDefault(this, 23, 0));
};


/**
 * @param {!proto.members.ProfileImageSetting} value
 * @return {!proto.members.Program} returns this
 */
proto.members.Program.prototype.setProfileimagesettings = function(value) {
  return jspb.Message.setProto3EnumField(this, 23, value);
};


/**
 * optional CustomExternalId applyFieldToExternalIdOnEnrol = 24;
 * @return {?proto.members.CustomExternalId}
 */
proto.members.Program.prototype.getApplyfieldtoexternalidonenrol = function() {
  return /** @type{?proto.members.CustomExternalId} */ (
    jspb.Message.getWrapperField(this, proto.members.CustomExternalId, 24));
};


/**
 * @param {?proto.members.CustomExternalId|undefined} value
 * @return {!proto.members.Program} returns this
*/
proto.members.Program.prototype.setApplyfieldtoexternalidonenrol = function(value) {
  return jspb.Message.setWrapperField(this, 24, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.members.Program} returns this
 */
proto.members.Program.prototype.clearApplyfieldtoexternalidonenrol = function() {
  return this.setApplyfieldtoexternalidonenrol(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.members.Program.prototype.hasApplyfieldtoexternalidonenrol = function() {
  return jspb.Message.getField(this, 24) != null;
};


/**
 * optional EventCaptureSettings eventCaptureSettings = 25;
 * @return {?proto.members.EventCaptureSettings}
 */
proto.members.Program.prototype.getEventcapturesettings = function() {
  return /** @type{?proto.members.EventCaptureSettings} */ (
    jspb.Message.getWrapperField(this, proto.members.EventCaptureSettings, 25));
};


/**
 * @param {?proto.members.EventCaptureSettings|undefined} value
 * @return {!proto.members.Program} returns this
*/
proto.members.Program.prototype.setEventcapturesettings = function(value) {
  return jspb.Message.setWrapperField(this, 25, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.members.Program} returns this
 */
proto.members.Program.prototype.clearEventcapturesettings = function() {
  return this.setEventcapturesettings(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.members.Program.prototype.hasEventcapturesettings = function() {
  return jspb.Message.getField(this, 25) != null;
};


/**
 * optional PassRecoverySettings passRecoverySettings = 26;
 * @return {?proto.members.PassRecoverySettings}
 */
proto.members.Program.prototype.getPassrecoverysettings = function() {
  return /** @type{?proto.members.PassRecoverySettings} */ (
    jspb.Message.getWrapperField(this, proto.members.PassRecoverySettings, 26));
};


/**
 * @param {?proto.members.PassRecoverySettings|undefined} value
 * @return {!proto.members.Program} returns this
*/
proto.members.Program.prototype.setPassrecoverysettings = function(value) {
  return jspb.Message.setWrapperField(this, 26, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.members.Program} returns this
 */
proto.members.Program.prototype.clearPassrecoverysettings = function() {
  return this.setPassrecoverysettings(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.members.Program.prototype.hasPassrecoverysettings = function() {
  return jspb.Message.getField(this, 26) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.members.EventCaptureSettings.prototype.toObject = function(opt_includeInstance) {
  return proto.members.EventCaptureSettings.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.members.EventCaptureSettings} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.members.EventCaptureSettings.toObject = function(includeInstance, msg) {
  var f, obj = {
    eventdataretentionsettingsMap: (f = msg.getEventdataretentionsettingsMap()) ? f.toObject(includeInstance, undefined) : [],
    smsconfirmuponcheckin: jspb.Message.getBooleanFieldWithDefault(msg, 2, false),
    emailconfirmuponcheckin: jspb.Message.getBooleanFieldWithDefault(msg, 3, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.members.EventCaptureSettings}
 */
proto.members.EventCaptureSettings.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.members.EventCaptureSettings;
  return proto.members.EventCaptureSettings.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.members.EventCaptureSettings} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.members.EventCaptureSettings}
 */
proto.members.EventCaptureSettings.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = msg.getEventdataretentionsettingsMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readUint32, jspb.BinaryReader.prototype.readUint32, null, 0, 0);
         });
      break;
    case 2:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setSmsconfirmuponcheckin(value);
      break;
    case 3:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setEmailconfirmuponcheckin(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.members.EventCaptureSettings.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.members.EventCaptureSettings.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.members.EventCaptureSettings} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.members.EventCaptureSettings.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getEventdataretentionsettingsMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(1, writer, jspb.BinaryWriter.prototype.writeUint32, jspb.BinaryWriter.prototype.writeUint32);
  }
  f = message.getSmsconfirmuponcheckin();
  if (f) {
    writer.writeBool(
      2,
      f
    );
  }
  f = message.getEmailconfirmuponcheckin();
  if (f) {
    writer.writeBool(
      3,
      f
    );
  }
};


/**
 * map<uint32, uint32> eventDataRetentionSettings = 1;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<number,number>}
 */
proto.members.EventCaptureSettings.prototype.getEventdataretentionsettingsMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<number,number>} */ (
      jspb.Message.getMapField(this, 1, opt_noLazyCreate,
      null));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.members.EventCaptureSettings} returns this
 */
proto.members.EventCaptureSettings.prototype.clearEventdataretentionsettingsMap = function() {
  this.getEventdataretentionsettingsMap().clear();
  return this;};


/**
 * optional bool smsConfirmUponCheckIn = 2;
 * @return {boolean}
 */
proto.members.EventCaptureSettings.prototype.getSmsconfirmuponcheckin = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 2, false));
};


/**
 * @param {boolean} value
 * @return {!proto.members.EventCaptureSettings} returns this
 */
proto.members.EventCaptureSettings.prototype.setSmsconfirmuponcheckin = function(value) {
  return jspb.Message.setProto3BooleanField(this, 2, value);
};


/**
 * optional bool emailConfirmUponCheckIn = 3;
 * @return {boolean}
 */
proto.members.EventCaptureSettings.prototype.getEmailconfirmuponcheckin = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 3, false));
};


/**
 * @param {boolean} value
 * @return {!proto.members.EventCaptureSettings} returns this
 */
proto.members.EventCaptureSettings.prototype.setEmailconfirmuponcheckin = function(value) {
  return jspb.Message.setProto3BooleanField(this, 3, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.members.ProgramCopyRequest.repeatedFields_ = [3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.members.ProgramCopyRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.members.ProgramCopyRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.members.ProgramCopyRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.members.ProgramCopyRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, ""),
    name: jspb.Message.getFieldWithDefault(msg, 2, ""),
    statusList: (f = jspb.Message.getRepeatedField(msg, 3)) == null ? undefined : f,
    passtypeidentifier: jspb.Message.getFieldWithDefault(msg, 4, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.members.ProgramCopyRequest}
 */
proto.members.ProgramCopyRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.members.ProgramCopyRequest;
  return proto.members.ProgramCopyRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.members.ProgramCopyRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.members.ProgramCopyRequest}
 */
proto.members.ProgramCopyRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 3:
      var values = /** @type {!Array<!proto.io.ProjectStatus>} */ (reader.isDelimited() ? reader.readPackedEnum() : [reader.readEnum()]);
      for (var i = 0; i < values.length; i++) {
        msg.addStatus(values[i]);
      }
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setPasstypeidentifier(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.members.ProgramCopyRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.members.ProgramCopyRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.members.ProgramCopyRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.members.ProgramCopyRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getStatusList();
  if (f.length > 0) {
    writer.writePackedEnum(
      3,
      f
    );
  }
  f = message.getPasstypeidentifier();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.members.ProgramCopyRequest.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.members.ProgramCopyRequest} returns this
 */
proto.members.ProgramCopyRequest.prototype.setId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string name = 2;
 * @return {string}
 */
proto.members.ProgramCopyRequest.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.members.ProgramCopyRequest} returns this
 */
proto.members.ProgramCopyRequest.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * repeated io.ProjectStatus status = 3;
 * @return {!Array<!proto.io.ProjectStatus>}
 */
proto.members.ProgramCopyRequest.prototype.getStatusList = function() {
  return /** @type {!Array<!proto.io.ProjectStatus>} */ (jspb.Message.getRepeatedField(this, 3));
};


/**
 * @param {!Array<!proto.io.ProjectStatus>} value
 * @return {!proto.members.ProgramCopyRequest} returns this
 */
proto.members.ProgramCopyRequest.prototype.setStatusList = function(value) {
  return jspb.Message.setField(this, 3, value || []);
};


/**
 * @param {!proto.io.ProjectStatus} value
 * @param {number=} opt_index
 * @return {!proto.members.ProgramCopyRequest} returns this
 */
proto.members.ProgramCopyRequest.prototype.addStatus = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 3, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.members.ProgramCopyRequest} returns this
 */
proto.members.ProgramCopyRequest.prototype.clearStatusList = function() {
  return this.setStatusList([]);
};


/**
 * optional string passTypeIdentifier = 4;
 * @return {string}
 */
proto.members.ProgramCopyRequest.prototype.getPasstypeidentifier = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.members.ProgramCopyRequest} returns this
 */
proto.members.ProgramCopyRequest.prototype.setPasstypeidentifier = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.members.ListProgramsResponse.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.members.ListProgramsResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.members.ListProgramsResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.members.ListProgramsResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.members.ListProgramsResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    programsList: jspb.Message.toObjectList(msg.getProgramsList(),
    proto.members.Program.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.members.ListProgramsResponse}
 */
proto.members.ListProgramsResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.members.ListProgramsResponse;
  return proto.members.ListProgramsResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.members.ListProgramsResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.members.ListProgramsResponse}
 */
proto.members.ListProgramsResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.members.Program;
      reader.readMessage(value,proto.members.Program.deserializeBinaryFromReader);
      msg.addPrograms(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.members.ListProgramsResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.members.ListProgramsResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.members.ListProgramsResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.members.ListProgramsResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getProgramsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.members.Program.serializeBinaryToWriter
    );
  }
};


/**
 * repeated Program programs = 1;
 * @return {!Array<!proto.members.Program>}
 */
proto.members.ListProgramsResponse.prototype.getProgramsList = function() {
  return /** @type{!Array<!proto.members.Program>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.members.Program, 1));
};


/**
 * @param {!Array<!proto.members.Program>} value
 * @return {!proto.members.ListProgramsResponse} returns this
*/
proto.members.ListProgramsResponse.prototype.setProgramsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.members.Program=} opt_value
 * @param {number=} opt_index
 * @return {!proto.members.Program}
 */
proto.members.ListProgramsResponse.prototype.addPrograms = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.members.Program, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.members.ListProgramsResponse} returns this
 */
proto.members.ListProgramsResponse.prototype.clearProgramsList = function() {
  return this.setProgramsList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.members.GetMetaKeysResponse.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.members.GetMetaKeysResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.members.GetMetaKeysResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.members.GetMetaKeysResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.members.GetMetaKeysResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    keysList: (f = jspb.Message.getRepeatedField(msg, 1)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.members.GetMetaKeysResponse}
 */
proto.members.GetMetaKeysResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.members.GetMetaKeysResponse;
  return proto.members.GetMetaKeysResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.members.GetMetaKeysResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.members.GetMetaKeysResponse}
 */
proto.members.GetMetaKeysResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.addKeys(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.members.GetMetaKeysResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.members.GetMetaKeysResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.members.GetMetaKeysResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.members.GetMetaKeysResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getKeysList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      1,
      f
    );
  }
};


/**
 * repeated string keys = 1;
 * @return {!Array<string>}
 */
proto.members.GetMetaKeysResponse.prototype.getKeysList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 1));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.members.GetMetaKeysResponse} returns this
 */
proto.members.GetMetaKeysResponse.prototype.setKeysList = function(value) {
  return jspb.Message.setField(this, 1, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.members.GetMetaKeysResponse} returns this
 */
proto.members.GetMetaKeysResponse.prototype.addKeys = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 1, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.members.GetMetaKeysResponse} returns this
 */
proto.members.GetMetaKeysResponse.prototype.clearKeysList = function() {
  return this.setKeysList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.members.CustomExternalId.prototype.toObject = function(opt_includeInstance) {
  return proto.members.CustomExternalId.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.members.CustomExternalId} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.members.CustomExternalId.toObject = function(includeInstance, msg) {
  var f, obj = {
    fielduniquename: jspb.Message.getFieldWithDefault(msg, 1, ""),
    errormessage: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.members.CustomExternalId}
 */
proto.members.CustomExternalId.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.members.CustomExternalId;
  return proto.members.CustomExternalId.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.members.CustomExternalId} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.members.CustomExternalId}
 */
proto.members.CustomExternalId.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setFielduniquename(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setErrormessage(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.members.CustomExternalId.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.members.CustomExternalId.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.members.CustomExternalId} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.members.CustomExternalId.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getFielduniquename();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getErrormessage();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional string fieldUniqueName = 1;
 * @return {string}
 */
proto.members.CustomExternalId.prototype.getFielduniquename = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.members.CustomExternalId} returns this
 */
proto.members.CustomExternalId.prototype.setFielduniquename = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string errorMessage = 2;
 * @return {string}
 */
proto.members.CustomExternalId.prototype.getErrormessage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.members.CustomExternalId} returns this
 */
proto.members.CustomExternalId.prototype.setErrormessage = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.members.PassRecoverySettings.repeatedFields_ = [5];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.members.PassRecoverySettings.prototype.toObject = function(opt_includeInstance) {
  return proto.members.PassRecoverySettings.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.members.PassRecoverySettings} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.members.PassRecoverySettings.toObject = function(includeInstance, msg) {
  var f, obj = {
    enabled: jspb.Message.getBooleanFieldWithDefault(msg, 1, false),
    delivery: jspb.Message.getFieldWithDefault(msg, 2, 0),
    errorpageheader: jspb.Message.getFieldWithDefault(msg, 3, ""),
    errorpagebody: jspb.Message.getFieldWithDefault(msg, 4, ""),
    fieldstomatchuponrecoveryList: (f = jspb.Message.getRepeatedField(msg, 5)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.members.PassRecoverySettings}
 */
proto.members.PassRecoverySettings.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.members.PassRecoverySettings;
  return proto.members.PassRecoverySettings.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.members.PassRecoverySettings} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.members.PassRecoverySettings}
 */
proto.members.PassRecoverySettings.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setEnabled(value);
      break;
    case 2:
      var value = /** @type {!proto.members.RecoverPassDelivery} */ (reader.readEnum());
      msg.setDelivery(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setErrorpageheader(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setErrorpagebody(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.addFieldstomatchuponrecovery(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.members.PassRecoverySettings.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.members.PassRecoverySettings.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.members.PassRecoverySettings} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.members.PassRecoverySettings.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getEnabled();
  if (f) {
    writer.writeBool(
      1,
      f
    );
  }
  f = message.getDelivery();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
  f = message.getErrorpageheader();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getErrorpagebody();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getFieldstomatchuponrecoveryList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      5,
      f
    );
  }
};


/**
 * optional bool enabled = 1;
 * @return {boolean}
 */
proto.members.PassRecoverySettings.prototype.getEnabled = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 1, false));
};


/**
 * @param {boolean} value
 * @return {!proto.members.PassRecoverySettings} returns this
 */
proto.members.PassRecoverySettings.prototype.setEnabled = function(value) {
  return jspb.Message.setProto3BooleanField(this, 1, value);
};


/**
 * optional RecoverPassDelivery delivery = 2;
 * @return {!proto.members.RecoverPassDelivery}
 */
proto.members.PassRecoverySettings.prototype.getDelivery = function() {
  return /** @type {!proto.members.RecoverPassDelivery} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {!proto.members.RecoverPassDelivery} value
 * @return {!proto.members.PassRecoverySettings} returns this
 */
proto.members.PassRecoverySettings.prototype.setDelivery = function(value) {
  return jspb.Message.setProto3EnumField(this, 2, value);
};


/**
 * optional string errorPageHeader = 3;
 * @return {string}
 */
proto.members.PassRecoverySettings.prototype.getErrorpageheader = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.members.PassRecoverySettings} returns this
 */
proto.members.PassRecoverySettings.prototype.setErrorpageheader = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string errorPageBody = 4;
 * @return {string}
 */
proto.members.PassRecoverySettings.prototype.getErrorpagebody = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.members.PassRecoverySettings} returns this
 */
proto.members.PassRecoverySettings.prototype.setErrorpagebody = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * repeated string fieldsToMatchUponRecovery = 5;
 * @return {!Array<string>}
 */
proto.members.PassRecoverySettings.prototype.getFieldstomatchuponrecoveryList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 5));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.members.PassRecoverySettings} returns this
 */
proto.members.PassRecoverySettings.prototype.setFieldstomatchuponrecoveryList = function(value) {
  return jspb.Message.setField(this, 5, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.members.PassRecoverySettings} returns this
 */
proto.members.PassRecoverySettings.prototype.addFieldstomatchuponrecovery = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 5, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.members.PassRecoverySettings} returns this
 */
proto.members.PassRecoverySettings.prototype.clearFieldstomatchuponrecoveryList = function() {
  return this.setFieldstomatchuponrecoveryList([]);
};


/**
 * @enum {number}
 */
proto.members.ProgramAutoUpDownGradeTierType = {
  UPDOWNGRADE_POINTS: 0,
  UPDOWNGRADE_SECONDARY_POINTS: 1,
  UPDOWNGRADE_TIER_POINTS: 2,
  UPDOWNGRADE_VISITS: 3
};

/**
 * @enum {number}
 */
proto.members.BalanceType = {
  BALANCE_TYPE_STRING: 0,
  BALANCE_TYPE_INT: 1,
  BALANCE_TYPE_DOUBLE: 2,
  BALANCE_TYPE_MONEY: 3
};

/**
 * @enum {number}
 */
proto.members.ProfileImageSetting = {
  PROFILE_IMAGE_NONE: 0,
  PROFILE_IMAGE_OPTIONAL: 1,
  PROFILE_IMAGE_REQUIRED: 2,
  PROFILE_IMAGE_RESTRICTED: 3
};

/**
 * @enum {number}
 */
proto.members.RecoverPassDelivery = {
  DELIVERY_REDIRECT: 0,
  DELIVERY_EMAIL: 1,
  DELIVERY_SMS: 2
};

goog.object.extend(exports, proto.members);
