// source: io/single_use_coupons/coupon.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() {
  if (this) { return this; }
  if (typeof window !== 'undefined') { return window; }
  if (typeof global !== 'undefined') { return global; }
  if (typeof self !== 'undefined') { return self; }
  return Function('return this')();
}.call(null));

var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js');
goog.object.extend(proto, google_protobuf_timestamp_pb);
var io_common_pagination_pb = require('../../io/common/pagination_pb.js');
goog.object.extend(proto, io_common_pagination_pb);
var io_common_filter_pb = require('../../io/common/filter_pb.js');
goog.object.extend(proto, io_common_filter_pb);
var io_common_pass_pb = require('../../io/common/pass_pb.js');
goog.object.extend(proto, io_common_pass_pb);
var io_common_personal_pb = require('../../io/common/personal_pb.js');
goog.object.extend(proto, io_common_personal_pb);
var io_common_metrics_pb = require('../../io/common/metrics_pb.js');
goog.object.extend(proto, io_common_metrics_pb);
goog.exportSymbol('proto.single_use_coupons.Coupon', null, global);
goog.exportSymbol('proto.single_use_coupons.CouponNewExternalIdRequest', null, global);
goog.exportSymbol('proto.single_use_coupons.CouponStatus', null, global);
goog.exportSymbol('proto.single_use_coupons.ExternalIdRequest', null, global);
goog.exportSymbol('proto.single_use_coupons.ListRequest', null, global);
goog.exportSymbol('proto.single_use_coupons.ListRequestDeprecated', null, global);
goog.exportSymbol('proto.single_use_coupons.RedemptionDetails', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.single_use_coupons.Coupon = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.single_use_coupons.Coupon, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.single_use_coupons.Coupon.displayName = 'proto.single_use_coupons.Coupon';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.single_use_coupons.RedemptionDetails = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.single_use_coupons.RedemptionDetails, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.single_use_coupons.RedemptionDetails.displayName = 'proto.single_use_coupons.RedemptionDetails';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.single_use_coupons.ExternalIdRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.single_use_coupons.ExternalIdRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.single_use_coupons.ExternalIdRequest.displayName = 'proto.single_use_coupons.ExternalIdRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.single_use_coupons.ListRequestDeprecated = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.single_use_coupons.ListRequestDeprecated, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.single_use_coupons.ListRequestDeprecated.displayName = 'proto.single_use_coupons.ListRequestDeprecated';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.single_use_coupons.ListRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.single_use_coupons.ListRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.single_use_coupons.ListRequest.displayName = 'proto.single_use_coupons.ListRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.single_use_coupons.CouponNewExternalIdRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.single_use_coupons.CouponNewExternalIdRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.single_use_coupons.CouponNewExternalIdRequest.displayName = 'proto.single_use_coupons.CouponNewExternalIdRequest';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.single_use_coupons.Coupon.prototype.toObject = function(opt_includeInstance) {
  return proto.single_use_coupons.Coupon.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.single_use_coupons.Coupon} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.single_use_coupons.Coupon.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, ""),
    externalid: jspb.Message.getFieldWithDefault(msg, 2, ""),
    offerid: jspb.Message.getFieldWithDefault(msg, 3, ""),
    campaignid: jspb.Message.getFieldWithDefault(msg, 4, ""),
    person: (f = msg.getPerson()) && io_common_personal_pb.Person.toObject(includeInstance, f),
    metadataMap: (f = msg.getMetadataMap()) ? f.toObject(includeInstance, undefined) : [],
    sku: jspb.Message.getFieldWithDefault(msg, 7, ""),
    optout: jspb.Message.getBooleanFieldWithDefault(msg, 8, false),
    status: jspb.Message.getFieldWithDefault(msg, 10, 0),
    expirydate: (f = msg.getExpirydate()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    redemptiondetails: (f = msg.getRedemptiondetails()) && proto.single_use_coupons.RedemptionDetails.toObject(includeInstance, f),
    passoverrides: (f = msg.getPassoverrides()) && io_common_pass_pb.PassOverrides.toObject(includeInstance, f),
    passmetadata: (f = msg.getPassmetadata()) && io_common_metrics_pb.Metadata.toObject(includeInstance, f),
    created: (f = msg.getCreated()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    updated: (f = msg.getUpdated()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.single_use_coupons.Coupon}
 */
proto.single_use_coupons.Coupon.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.single_use_coupons.Coupon;
  return proto.single_use_coupons.Coupon.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.single_use_coupons.Coupon} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.single_use_coupons.Coupon}
 */
proto.single_use_coupons.Coupon.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setExternalid(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setOfferid(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setCampaignid(value);
      break;
    case 5:
      var value = new io_common_personal_pb.Person;
      reader.readMessage(value,io_common_personal_pb.Person.deserializeBinaryFromReader);
      msg.setPerson(value);
      break;
    case 6:
      var value = msg.getMetadataMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readString, null, "", "");
         });
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setSku(value);
      break;
    case 8:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setOptout(value);
      break;
    case 10:
      var value = /** @type {!proto.single_use_coupons.CouponStatus} */ (reader.readEnum());
      msg.setStatus(value);
      break;
    case 11:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setExpirydate(value);
      break;
    case 12:
      var value = new proto.single_use_coupons.RedemptionDetails;
      reader.readMessage(value,proto.single_use_coupons.RedemptionDetails.deserializeBinaryFromReader);
      msg.setRedemptiondetails(value);
      break;
    case 13:
      var value = new io_common_pass_pb.PassOverrides;
      reader.readMessage(value,io_common_pass_pb.PassOverrides.deserializeBinaryFromReader);
      msg.setPassoverrides(value);
      break;
    case 14:
      var value = new io_common_metrics_pb.Metadata;
      reader.readMessage(value,io_common_metrics_pb.Metadata.deserializeBinaryFromReader);
      msg.setPassmetadata(value);
      break;
    case 15:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setCreated(value);
      break;
    case 16:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setUpdated(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.single_use_coupons.Coupon.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.single_use_coupons.Coupon.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.single_use_coupons.Coupon} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.single_use_coupons.Coupon.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getExternalid();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getOfferid();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getCampaignid();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getPerson();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      io_common_personal_pb.Person.serializeBinaryToWriter
    );
  }
  f = message.getMetadataMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(6, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeString);
  }
  f = message.getSku();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getOptout();
  if (f) {
    writer.writeBool(
      8,
      f
    );
  }
  f = message.getStatus();
  if (f !== 0.0) {
    writer.writeEnum(
      10,
      f
    );
  }
  f = message.getExpirydate();
  if (f != null) {
    writer.writeMessage(
      11,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getRedemptiondetails();
  if (f != null) {
    writer.writeMessage(
      12,
      f,
      proto.single_use_coupons.RedemptionDetails.serializeBinaryToWriter
    );
  }
  f = message.getPassoverrides();
  if (f != null) {
    writer.writeMessage(
      13,
      f,
      io_common_pass_pb.PassOverrides.serializeBinaryToWriter
    );
  }
  f = message.getPassmetadata();
  if (f != null) {
    writer.writeMessage(
      14,
      f,
      io_common_metrics_pb.Metadata.serializeBinaryToWriter
    );
  }
  f = message.getCreated();
  if (f != null) {
    writer.writeMessage(
      15,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getUpdated();
  if (f != null) {
    writer.writeMessage(
      16,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.single_use_coupons.Coupon.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.single_use_coupons.Coupon} returns this
 */
proto.single_use_coupons.Coupon.prototype.setId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string externalId = 2;
 * @return {string}
 */
proto.single_use_coupons.Coupon.prototype.getExternalid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.single_use_coupons.Coupon} returns this
 */
proto.single_use_coupons.Coupon.prototype.setExternalid = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string offerId = 3;
 * @return {string}
 */
proto.single_use_coupons.Coupon.prototype.getOfferid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.single_use_coupons.Coupon} returns this
 */
proto.single_use_coupons.Coupon.prototype.setOfferid = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string campaignId = 4;
 * @return {string}
 */
proto.single_use_coupons.Coupon.prototype.getCampaignid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.single_use_coupons.Coupon} returns this
 */
proto.single_use_coupons.Coupon.prototype.setCampaignid = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional io.Person person = 5;
 * @return {?proto.io.Person}
 */
proto.single_use_coupons.Coupon.prototype.getPerson = function() {
  return /** @type{?proto.io.Person} */ (
    jspb.Message.getWrapperField(this, io_common_personal_pb.Person, 5));
};


/**
 * @param {?proto.io.Person|undefined} value
 * @return {!proto.single_use_coupons.Coupon} returns this
*/
proto.single_use_coupons.Coupon.prototype.setPerson = function(value) {
  return jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.single_use_coupons.Coupon} returns this
 */
proto.single_use_coupons.Coupon.prototype.clearPerson = function() {
  return this.setPerson(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.single_use_coupons.Coupon.prototype.hasPerson = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * map<string, string> metaData = 6;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,string>}
 */
proto.single_use_coupons.Coupon.prototype.getMetadataMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,string>} */ (
      jspb.Message.getMapField(this, 6, opt_noLazyCreate,
      null));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.single_use_coupons.Coupon} returns this
 */
proto.single_use_coupons.Coupon.prototype.clearMetadataMap = function() {
  this.getMetadataMap().clear();
  return this;};


/**
 * optional string sku = 7;
 * @return {string}
 */
proto.single_use_coupons.Coupon.prototype.getSku = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.single_use_coupons.Coupon} returns this
 */
proto.single_use_coupons.Coupon.prototype.setSku = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * optional bool optOut = 8;
 * @return {boolean}
 */
proto.single_use_coupons.Coupon.prototype.getOptout = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 8, false));
};


/**
 * @param {boolean} value
 * @return {!proto.single_use_coupons.Coupon} returns this
 */
proto.single_use_coupons.Coupon.prototype.setOptout = function(value) {
  return jspb.Message.setProto3BooleanField(this, 8, value);
};


/**
 * optional CouponStatus status = 10;
 * @return {!proto.single_use_coupons.CouponStatus}
 */
proto.single_use_coupons.Coupon.prototype.getStatus = function() {
  return /** @type {!proto.single_use_coupons.CouponStatus} */ (jspb.Message.getFieldWithDefault(this, 10, 0));
};


/**
 * @param {!proto.single_use_coupons.CouponStatus} value
 * @return {!proto.single_use_coupons.Coupon} returns this
 */
proto.single_use_coupons.Coupon.prototype.setStatus = function(value) {
  return jspb.Message.setProto3EnumField(this, 10, value);
};


/**
 * optional google.protobuf.Timestamp expiryDate = 11;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.single_use_coupons.Coupon.prototype.getExpirydate = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 11));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.single_use_coupons.Coupon} returns this
*/
proto.single_use_coupons.Coupon.prototype.setExpirydate = function(value) {
  return jspb.Message.setWrapperField(this, 11, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.single_use_coupons.Coupon} returns this
 */
proto.single_use_coupons.Coupon.prototype.clearExpirydate = function() {
  return this.setExpirydate(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.single_use_coupons.Coupon.prototype.hasExpirydate = function() {
  return jspb.Message.getField(this, 11) != null;
};


/**
 * optional RedemptionDetails redemptionDetails = 12;
 * @return {?proto.single_use_coupons.RedemptionDetails}
 */
proto.single_use_coupons.Coupon.prototype.getRedemptiondetails = function() {
  return /** @type{?proto.single_use_coupons.RedemptionDetails} */ (
    jspb.Message.getWrapperField(this, proto.single_use_coupons.RedemptionDetails, 12));
};


/**
 * @param {?proto.single_use_coupons.RedemptionDetails|undefined} value
 * @return {!proto.single_use_coupons.Coupon} returns this
*/
proto.single_use_coupons.Coupon.prototype.setRedemptiondetails = function(value) {
  return jspb.Message.setWrapperField(this, 12, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.single_use_coupons.Coupon} returns this
 */
proto.single_use_coupons.Coupon.prototype.clearRedemptiondetails = function() {
  return this.setRedemptiondetails(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.single_use_coupons.Coupon.prototype.hasRedemptiondetails = function() {
  return jspb.Message.getField(this, 12) != null;
};


/**
 * optional io.PassOverrides passOverrides = 13;
 * @return {?proto.io.PassOverrides}
 */
proto.single_use_coupons.Coupon.prototype.getPassoverrides = function() {
  return /** @type{?proto.io.PassOverrides} */ (
    jspb.Message.getWrapperField(this, io_common_pass_pb.PassOverrides, 13));
};


/**
 * @param {?proto.io.PassOverrides|undefined} value
 * @return {!proto.single_use_coupons.Coupon} returns this
*/
proto.single_use_coupons.Coupon.prototype.setPassoverrides = function(value) {
  return jspb.Message.setWrapperField(this, 13, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.single_use_coupons.Coupon} returns this
 */
proto.single_use_coupons.Coupon.prototype.clearPassoverrides = function() {
  return this.setPassoverrides(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.single_use_coupons.Coupon.prototype.hasPassoverrides = function() {
  return jspb.Message.getField(this, 13) != null;
};


/**
 * optional io.Metadata passMetaData = 14;
 * @return {?proto.io.Metadata}
 */
proto.single_use_coupons.Coupon.prototype.getPassmetadata = function() {
  return /** @type{?proto.io.Metadata} */ (
    jspb.Message.getWrapperField(this, io_common_metrics_pb.Metadata, 14));
};


/**
 * @param {?proto.io.Metadata|undefined} value
 * @return {!proto.single_use_coupons.Coupon} returns this
*/
proto.single_use_coupons.Coupon.prototype.setPassmetadata = function(value) {
  return jspb.Message.setWrapperField(this, 14, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.single_use_coupons.Coupon} returns this
 */
proto.single_use_coupons.Coupon.prototype.clearPassmetadata = function() {
  return this.setPassmetadata(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.single_use_coupons.Coupon.prototype.hasPassmetadata = function() {
  return jspb.Message.getField(this, 14) != null;
};


/**
 * optional google.protobuf.Timestamp created = 15;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.single_use_coupons.Coupon.prototype.getCreated = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 15));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.single_use_coupons.Coupon} returns this
*/
proto.single_use_coupons.Coupon.prototype.setCreated = function(value) {
  return jspb.Message.setWrapperField(this, 15, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.single_use_coupons.Coupon} returns this
 */
proto.single_use_coupons.Coupon.prototype.clearCreated = function() {
  return this.setCreated(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.single_use_coupons.Coupon.prototype.hasCreated = function() {
  return jspb.Message.getField(this, 15) != null;
};


/**
 * optional google.protobuf.Timestamp updated = 16;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.single_use_coupons.Coupon.prototype.getUpdated = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 16));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.single_use_coupons.Coupon} returns this
*/
proto.single_use_coupons.Coupon.prototype.setUpdated = function(value) {
  return jspb.Message.setWrapperField(this, 16, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.single_use_coupons.Coupon} returns this
 */
proto.single_use_coupons.Coupon.prototype.clearUpdated = function() {
  return this.setUpdated(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.single_use_coupons.Coupon.prototype.hasUpdated = function() {
  return jspb.Message.getField(this, 16) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.single_use_coupons.RedemptionDetails.prototype.toObject = function(opt_includeInstance) {
  return proto.single_use_coupons.RedemptionDetails.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.single_use_coupons.RedemptionDetails} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.single_use_coupons.RedemptionDetails.toObject = function(includeInstance, msg) {
  var f, obj = {
    redemptiondate: (f = msg.getRedemptiondate()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    redemptioncode: jspb.Message.getFieldWithDefault(msg, 2, ""),
    lat: jspb.Message.getFloatingPointFieldWithDefault(msg, 3, 0.0),
    lon: jspb.Message.getFloatingPointFieldWithDefault(msg, 4, 0.0),
    alt: jspb.Message.getFieldWithDefault(msg, 5, 0),
    redemptionsource: jspb.Message.getFieldWithDefault(msg, 6, ""),
    redemptionreference: jspb.Message.getFieldWithDefault(msg, 7, ""),
    transactionreference: jspb.Message.getFieldWithDefault(msg, 8, ""),
    transactionamount: jspb.Message.getFloatingPointFieldWithDefault(msg, 9, 0.0),
    metadataMap: (f = msg.getMetadataMap()) ? f.toObject(includeInstance, undefined) : []
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.single_use_coupons.RedemptionDetails}
 */
proto.single_use_coupons.RedemptionDetails.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.single_use_coupons.RedemptionDetails;
  return proto.single_use_coupons.RedemptionDetails.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.single_use_coupons.RedemptionDetails} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.single_use_coupons.RedemptionDetails}
 */
proto.single_use_coupons.RedemptionDetails.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setRedemptiondate(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setRedemptioncode(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setLat(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setLon(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setAlt(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setRedemptionsource(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setRedemptionreference(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setTransactionreference(value);
      break;
    case 9:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setTransactionamount(value);
      break;
    case 10:
      var value = msg.getMetadataMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readString, null, "", "");
         });
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.single_use_coupons.RedemptionDetails.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.single_use_coupons.RedemptionDetails.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.single_use_coupons.RedemptionDetails} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.single_use_coupons.RedemptionDetails.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getRedemptiondate();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getRedemptioncode();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getLat();
  if (f !== 0.0) {
    writer.writeDouble(
      3,
      f
    );
  }
  f = message.getLon();
  if (f !== 0.0) {
    writer.writeDouble(
      4,
      f
    );
  }
  f = message.getAlt();
  if (f !== 0) {
    writer.writeInt32(
      5,
      f
    );
  }
  f = message.getRedemptionsource();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getRedemptionreference();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getTransactionreference();
  if (f.length > 0) {
    writer.writeString(
      8,
      f
    );
  }
  f = message.getTransactionamount();
  if (f !== 0.0) {
    writer.writeDouble(
      9,
      f
    );
  }
  f = message.getMetadataMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(10, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeString);
  }
};


/**
 * optional google.protobuf.Timestamp redemptionDate = 1;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.single_use_coupons.RedemptionDetails.prototype.getRedemptiondate = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 1));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.single_use_coupons.RedemptionDetails} returns this
*/
proto.single_use_coupons.RedemptionDetails.prototype.setRedemptiondate = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.single_use_coupons.RedemptionDetails} returns this
 */
proto.single_use_coupons.RedemptionDetails.prototype.clearRedemptiondate = function() {
  return this.setRedemptiondate(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.single_use_coupons.RedemptionDetails.prototype.hasRedemptiondate = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string redemptionCode = 2;
 * @return {string}
 */
proto.single_use_coupons.RedemptionDetails.prototype.getRedemptioncode = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.single_use_coupons.RedemptionDetails} returns this
 */
proto.single_use_coupons.RedemptionDetails.prototype.setRedemptioncode = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional double lat = 3;
 * @return {number}
 */
proto.single_use_coupons.RedemptionDetails.prototype.getLat = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 3, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.single_use_coupons.RedemptionDetails} returns this
 */
proto.single_use_coupons.RedemptionDetails.prototype.setLat = function(value) {
  return jspb.Message.setProto3FloatField(this, 3, value);
};


/**
 * optional double lon = 4;
 * @return {number}
 */
proto.single_use_coupons.RedemptionDetails.prototype.getLon = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 4, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.single_use_coupons.RedemptionDetails} returns this
 */
proto.single_use_coupons.RedemptionDetails.prototype.setLon = function(value) {
  return jspb.Message.setProto3FloatField(this, 4, value);
};


/**
 * optional int32 alt = 5;
 * @return {number}
 */
proto.single_use_coupons.RedemptionDetails.prototype.getAlt = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.single_use_coupons.RedemptionDetails} returns this
 */
proto.single_use_coupons.RedemptionDetails.prototype.setAlt = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional string redemptionSource = 6;
 * @return {string}
 */
proto.single_use_coupons.RedemptionDetails.prototype.getRedemptionsource = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.single_use_coupons.RedemptionDetails} returns this
 */
proto.single_use_coupons.RedemptionDetails.prototype.setRedemptionsource = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional string redemptionReference = 7;
 * @return {string}
 */
proto.single_use_coupons.RedemptionDetails.prototype.getRedemptionreference = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.single_use_coupons.RedemptionDetails} returns this
 */
proto.single_use_coupons.RedemptionDetails.prototype.setRedemptionreference = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * optional string transactionReference = 8;
 * @return {string}
 */
proto.single_use_coupons.RedemptionDetails.prototype.getTransactionreference = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/**
 * @param {string} value
 * @return {!proto.single_use_coupons.RedemptionDetails} returns this
 */
proto.single_use_coupons.RedemptionDetails.prototype.setTransactionreference = function(value) {
  return jspb.Message.setProto3StringField(this, 8, value);
};


/**
 * optional double transactionAmount = 9;
 * @return {number}
 */
proto.single_use_coupons.RedemptionDetails.prototype.getTransactionamount = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 9, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.single_use_coupons.RedemptionDetails} returns this
 */
proto.single_use_coupons.RedemptionDetails.prototype.setTransactionamount = function(value) {
  return jspb.Message.setProto3FloatField(this, 9, value);
};


/**
 * map<string, string> metaData = 10;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,string>}
 */
proto.single_use_coupons.RedemptionDetails.prototype.getMetadataMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,string>} */ (
      jspb.Message.getMapField(this, 10, opt_noLazyCreate,
      null));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.single_use_coupons.RedemptionDetails} returns this
 */
proto.single_use_coupons.RedemptionDetails.prototype.clearMetadataMap = function() {
  this.getMetadataMap().clear();
  return this;};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.single_use_coupons.ExternalIdRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.single_use_coupons.ExternalIdRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.single_use_coupons.ExternalIdRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.single_use_coupons.ExternalIdRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    couponcampaignid: jspb.Message.getFieldWithDefault(msg, 1, ""),
    externalid: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.single_use_coupons.ExternalIdRequest}
 */
proto.single_use_coupons.ExternalIdRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.single_use_coupons.ExternalIdRequest;
  return proto.single_use_coupons.ExternalIdRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.single_use_coupons.ExternalIdRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.single_use_coupons.ExternalIdRequest}
 */
proto.single_use_coupons.ExternalIdRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setCouponcampaignid(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setExternalid(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.single_use_coupons.ExternalIdRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.single_use_coupons.ExternalIdRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.single_use_coupons.ExternalIdRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.single_use_coupons.ExternalIdRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCouponcampaignid();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getExternalid();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional string couponCampaignId = 1;
 * @return {string}
 */
proto.single_use_coupons.ExternalIdRequest.prototype.getCouponcampaignid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.single_use_coupons.ExternalIdRequest} returns this
 */
proto.single_use_coupons.ExternalIdRequest.prototype.setCouponcampaignid = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string externalId = 2;
 * @return {string}
 */
proto.single_use_coupons.ExternalIdRequest.prototype.getExternalid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.single_use_coupons.ExternalIdRequest} returns this
 */
proto.single_use_coupons.ExternalIdRequest.prototype.setExternalid = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.single_use_coupons.ListRequestDeprecated.prototype.toObject = function(opt_includeInstance) {
  return proto.single_use_coupons.ListRequestDeprecated.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.single_use_coupons.ListRequestDeprecated} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.single_use_coupons.ListRequestDeprecated.toObject = function(includeInstance, msg) {
  var f, obj = {
    couponcampaignid: jspb.Message.getFieldWithDefault(msg, 1, ""),
    pagination: (f = msg.getPagination()) && io_common_pagination_pb.Pagination.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.single_use_coupons.ListRequestDeprecated}
 */
proto.single_use_coupons.ListRequestDeprecated.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.single_use_coupons.ListRequestDeprecated;
  return proto.single_use_coupons.ListRequestDeprecated.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.single_use_coupons.ListRequestDeprecated} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.single_use_coupons.ListRequestDeprecated}
 */
proto.single_use_coupons.ListRequestDeprecated.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setCouponcampaignid(value);
      break;
    case 2:
      var value = new io_common_pagination_pb.Pagination;
      reader.readMessage(value,io_common_pagination_pb.Pagination.deserializeBinaryFromReader);
      msg.setPagination(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.single_use_coupons.ListRequestDeprecated.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.single_use_coupons.ListRequestDeprecated.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.single_use_coupons.ListRequestDeprecated} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.single_use_coupons.ListRequestDeprecated.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCouponcampaignid();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getPagination();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      io_common_pagination_pb.Pagination.serializeBinaryToWriter
    );
  }
};


/**
 * optional string couponCampaignId = 1;
 * @return {string}
 */
proto.single_use_coupons.ListRequestDeprecated.prototype.getCouponcampaignid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.single_use_coupons.ListRequestDeprecated} returns this
 */
proto.single_use_coupons.ListRequestDeprecated.prototype.setCouponcampaignid = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional io.Pagination pagination = 2;
 * @return {?proto.io.Pagination}
 */
proto.single_use_coupons.ListRequestDeprecated.prototype.getPagination = function() {
  return /** @type{?proto.io.Pagination} */ (
    jspb.Message.getWrapperField(this, io_common_pagination_pb.Pagination, 2));
};


/**
 * @param {?proto.io.Pagination|undefined} value
 * @return {!proto.single_use_coupons.ListRequestDeprecated} returns this
*/
proto.single_use_coupons.ListRequestDeprecated.prototype.setPagination = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.single_use_coupons.ListRequestDeprecated} returns this
 */
proto.single_use_coupons.ListRequestDeprecated.prototype.clearPagination = function() {
  return this.setPagination(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.single_use_coupons.ListRequestDeprecated.prototype.hasPagination = function() {
  return jspb.Message.getField(this, 2) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.single_use_coupons.ListRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.single_use_coupons.ListRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.single_use_coupons.ListRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.single_use_coupons.ListRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    couponcampaignid: jspb.Message.getFieldWithDefault(msg, 1, ""),
    filters: (f = msg.getFilters()) && io_common_filter_pb.Filters.toObject(includeInstance, f),
    emailascsv: jspb.Message.getBooleanFieldWithDefault(msg, 3, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.single_use_coupons.ListRequest}
 */
proto.single_use_coupons.ListRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.single_use_coupons.ListRequest;
  return proto.single_use_coupons.ListRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.single_use_coupons.ListRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.single_use_coupons.ListRequest}
 */
proto.single_use_coupons.ListRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setCouponcampaignid(value);
      break;
    case 2:
      var value = new io_common_filter_pb.Filters;
      reader.readMessage(value,io_common_filter_pb.Filters.deserializeBinaryFromReader);
      msg.setFilters(value);
      break;
    case 3:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setEmailascsv(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.single_use_coupons.ListRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.single_use_coupons.ListRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.single_use_coupons.ListRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.single_use_coupons.ListRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCouponcampaignid();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getFilters();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      io_common_filter_pb.Filters.serializeBinaryToWriter
    );
  }
  f = message.getEmailascsv();
  if (f) {
    writer.writeBool(
      3,
      f
    );
  }
};


/**
 * optional string couponCampaignId = 1;
 * @return {string}
 */
proto.single_use_coupons.ListRequest.prototype.getCouponcampaignid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.single_use_coupons.ListRequest} returns this
 */
proto.single_use_coupons.ListRequest.prototype.setCouponcampaignid = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional io.Filters filters = 2;
 * @return {?proto.io.Filters}
 */
proto.single_use_coupons.ListRequest.prototype.getFilters = function() {
  return /** @type{?proto.io.Filters} */ (
    jspb.Message.getWrapperField(this, io_common_filter_pb.Filters, 2));
};


/**
 * @param {?proto.io.Filters|undefined} value
 * @return {!proto.single_use_coupons.ListRequest} returns this
*/
proto.single_use_coupons.ListRequest.prototype.setFilters = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.single_use_coupons.ListRequest} returns this
 */
proto.single_use_coupons.ListRequest.prototype.clearFilters = function() {
  return this.setFilters(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.single_use_coupons.ListRequest.prototype.hasFilters = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional bool emailAsCsv = 3;
 * @return {boolean}
 */
proto.single_use_coupons.ListRequest.prototype.getEmailascsv = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 3, false));
};


/**
 * @param {boolean} value
 * @return {!proto.single_use_coupons.ListRequest} returns this
 */
proto.single_use_coupons.ListRequest.prototype.setEmailascsv = function(value) {
  return jspb.Message.setProto3BooleanField(this, 3, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.single_use_coupons.CouponNewExternalIdRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.single_use_coupons.CouponNewExternalIdRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.single_use_coupons.CouponNewExternalIdRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.single_use_coupons.CouponNewExternalIdRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, ""),
    couponcampaignid: jspb.Message.getFieldWithDefault(msg, 2, ""),
    externalid: jspb.Message.getFieldWithDefault(msg, 3, ""),
    newexternalid: jspb.Message.getFieldWithDefault(msg, 4, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.single_use_coupons.CouponNewExternalIdRequest}
 */
proto.single_use_coupons.CouponNewExternalIdRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.single_use_coupons.CouponNewExternalIdRequest;
  return proto.single_use_coupons.CouponNewExternalIdRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.single_use_coupons.CouponNewExternalIdRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.single_use_coupons.CouponNewExternalIdRequest}
 */
proto.single_use_coupons.CouponNewExternalIdRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setCouponcampaignid(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setExternalid(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setNewexternalid(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.single_use_coupons.CouponNewExternalIdRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.single_use_coupons.CouponNewExternalIdRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.single_use_coupons.CouponNewExternalIdRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.single_use_coupons.CouponNewExternalIdRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getCouponcampaignid();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getExternalid();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getNewexternalid();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.single_use_coupons.CouponNewExternalIdRequest.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.single_use_coupons.CouponNewExternalIdRequest} returns this
 */
proto.single_use_coupons.CouponNewExternalIdRequest.prototype.setId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string couponCampaignId = 2;
 * @return {string}
 */
proto.single_use_coupons.CouponNewExternalIdRequest.prototype.getCouponcampaignid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.single_use_coupons.CouponNewExternalIdRequest} returns this
 */
proto.single_use_coupons.CouponNewExternalIdRequest.prototype.setCouponcampaignid = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string externalId = 3;
 * @return {string}
 */
proto.single_use_coupons.CouponNewExternalIdRequest.prototype.getExternalid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.single_use_coupons.CouponNewExternalIdRequest} returns this
 */
proto.single_use_coupons.CouponNewExternalIdRequest.prototype.setExternalid = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string newExternalId = 4;
 * @return {string}
 */
proto.single_use_coupons.CouponNewExternalIdRequest.prototype.getNewexternalid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.single_use_coupons.CouponNewExternalIdRequest} returns this
 */
proto.single_use_coupons.CouponNewExternalIdRequest.prototype.setNewexternalid = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * @enum {number}
 */
proto.single_use_coupons.CouponStatus = {
  UNREDEEMED: 0,
  REDEEMED: 1
};

goog.object.extend(exports, proto.single_use_coupons);
